version: "3.1"
services:

    crowdsourcemail:
        build:
            context: .
            dockerfile: dockerfiles/local/Dockerfile
        image: crowdsourcemail:latest
        volumes:
            - ./src:/application
        ports:
            - "1984:8080"
