version: "3.1"
services:

    crowdsourcemail:
        restart: unless-stopped
        build:
            context: .
            dockerfile: dockerfiles/local/Dockerfile
        image: crowdsourcemail:latest
        environment:
            - DJANGO_SECRET=secret-after-this-${DJANGO_SECRET}
            - GMAIL_USER=${GMAIL_USER}
            - GMAIL_PASSWORD=${GMAIL_PASSWORD}
            - HOST=${HOST}
            - ENV=env_${ENV}
        volumes:
            - ./src:/application
        ports:
            - 1985:8080
        command: ["bash", "server.sh"]

    management-commands:
        restart: unless-stopped
        build:
            context: .
            dockerfile: dockerfiles/local/Dockerfile
        image: crowdsourcemail:latest
        environment:
            - DJANGO_SECRET=secret-after-this-${DJANGO_SECRET}
            - GMAIL_USER=${GMAIL_USER}
            - GMAIL_PASSWORD=${GMAIL_PASSWORD}
        volumes:
            - ./src:/application
        command: ["bash", "management.sh"]

    frontend:
        restart: unless-stopped
        build:
            context: .
            dockerfile: dockerfiles/nginx/Dockerfile
        image: frontend:latest
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - ./src/frontend:/home/www-data/static
        ports:
            - 1986:80
            - 1987:443
