version: "3.1"
services:

    crowdsourcemail:
        build:
            context: .
            dockerfile: dockerfiles/local/Dockerfile
        image: crowdsourcemail:latest
        environment:
            - DJANGO_SECRET=secret-after-this-${DJANGO_SECRET}
        volumes:
            - ./src:/application
        ports:
            - "1984:8080"
        command: ["python", "./crowdsourcemail/manage.py", "runserver", "0:8080"]
