version: "3.1"
services:

    crowdsourcemail:
        restart: unless-stopped
        build:
            context: .
            dockerfile: dockerfiles/crowdsourcemail/Dockerfile
        image: crowdsourcemail:latest
        environment:
            - DJANGO_SECRET=secret-after-this-${DJANGO_SECRET}
            - GMAIL_USER=${GMAIL_USER}
            - GMAIL_PASSWORD=${GMAIL_PASSWORD}
            - HOST=${HOST}
            - CDN_HOST=${CDN_HOST}
            - ENV=env_${ENV}
        volumes:
            - ./src:/application
        ports:
            - ${CROWDSOURCEMAIL_PORT}:8080
            - 3000:3000
        command: ["bash", "server.sh"]

    management-commands:
        restart: unless-stopped
        build:
            context: .
            dockerfile: dockerfiles/crowdsourcemail/Dockerfile
        image: crowdsourcemail:latest
        environment:
            - DJANGO_SECRET=secret-after-this-${DJANGO_SECRET}
            - GMAIL_USER=${GMAIL_USER}
            - GMAIL_PASSWORD=${GMAIL_PASSWORD}
            - CROWDSOURCEMAIL_WEBHOOKS=${CROWDSOURCEMAIL_WEBHOOKS}
        volumes:
            - ./src:/application
        command: ["bash", "management.sh"]

    frontend:
        restart: unless-stopped
        build:
            context: .
            dockerfile: dockerfiles/frontend/Dockerfile
        image: frontend:nginx-webpack
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - ./src/frontend:/home/www-data/static
        ports:
            - ${FRONTEND_PORT}:80

    discord-bot:
        build:
            context: .
            dockerfile: dockerfiles/discord-bot/Dockerfile
        volumes:
            - ./src/discord-bot:/code
        environment:
            TOKEN: "${DISCORD_TOKEN}"
            CLIENT_ID: "${CLIENT_ID}"
            AUDIT_LOG_WEBHOOK: "${AUDIT_LOG_WEBHOOK}"
        command: ["bash", "server.sh"]
