# Generated by Django 3.2.4 on 2021-07-31 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_mailbox', '0009_auto_20210719_1121'),
        ('mail', '0002_alter_mailsettings_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(db_index=True, max_length=255, unique=True)),
                ('message', models.ManyToManyField(related_name='mail_tags', to='django_mailbox.Message')),
            ],
        ),
    ]
