# Generated by Django 3.2.4 on 2021-08-01 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0003_mailtag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mailtag',
            old_name='message',
            new_name='messages',
        ),
    ]
