# Generated by Django 3.2.4 on 2021-08-01 17:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mail', '0004_rename_message_mailtag_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailtag',
            name='users',
            field=models.ManyToManyField(related_name='mail_tags', to=settings.AUTH_USER_MODEL),
        ),
    ]
