# Generated by Django 3.2.4 on 2021-08-01 21:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('django_mailbox', '0009_auto_20210719_1121'),
        ('mail', '0005_mailtag_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMailTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_mail_tags', to='django_mailbox.message')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_mail_tags', to='mail.mailtag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_mail_tags', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
