# Generated by Django 3.2.4 on 2021-11-02 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0007_usermailvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermailvote',
            name='vote',
            field=models.IntegerField(default=0),
        ),
    ]
